version: "3.5"
services:
  web:
    image: ${IMAGE_NAME:-mcano/compose-to-swarm:v1}
    environment:
      - REDIS_HOST=redis
      - DOCKER_SERVICE_NAME={{.Service.Name}}.{{.Task.Slot}}
      - FOO=${FOO:-BAR}
    ports:
      - target: 5000
        published: 5000
    networks:
      - skynet
    deploy:
      replicas: ${DEPLOYMENT_REPLICAS:-3}
      restart_policy:
        # restart under any condition
        condition: any
      update_config:
        # update one task at a time
        parallelism: 1
        # update after 10s passed and container is healthy
        delay: 10s
        # spin up a new container first
        order: start-first

  redis:
    image: "redis:alpine"
    deploy:
      replicas: 1
    networks:
      skynet:

networks:
  skynet:
